import type { Card } from "../models/game.model.js";

export const cards: Card[] = [
  { id: 1, value: "🐶", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 2, value: "🐶", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 3, value: "🐱", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 4, value: "🐱", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 5, value: "🐭", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 6, value: "🐭", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 7, value: "🐹", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 8, value: "🐹", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 9, value: "🐰", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 10, value: "🐰", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 11, value: "🦊", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 12, value: "🦊", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 13, value: "🐻", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 14, value: "🐻", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 15, value: "🐼", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 16, value: "🐼", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 17, value: "🐨", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 18, value: "🐨", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 19, value: "🐯", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 20, value: "🐯", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 21, value: "🦁", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 22, value: "🦁", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 23, value: "🐮", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 24, value: "🐮", isFlipped: false, isMatched: false, isWildcard: false },
  { id: 25, value: "🌟", isFlipped: false, isMatched: false, isWildcard: true },
];
